version: "3"
services:
  mqtt-broker:
    image: eclipse-mosquitto
    container_name: mqtt-broker
    expose:
      - 1883
    ports:
      - 1883:1883
    restart: unless-stopped
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./logs:/mosquitto/log  # for mosquitto log
      - ./broker:/broker
    environment:
      - TZ=Europe/Paris  # timezone setting
    networks: # for network delay setting
      - mqtt_network

  mqtt-publisher:
    # image: eclipse-mosquitto
    build: ./custom_mosquitto
    container_name: mqtt-publisher
    command: ./publisher/pub_message.sh  # run publisher script
    depends_on:
      - mqtt-broker
    volumes:
      - ./logs:/logs # for mosquitto log
      - ./publisher:/publisher  # publisher script
    environment:
      - TZ=Europe/Paris  # timezone setting
    networks: # for network delay setting
      - mqtt_network
    cap_add:
      - NET_ADMIN  # for network delay setting

  mqtt-subscriber:
    # image: eclipse-mosquitto
    build: ./custom_mosquitto
    container_name: mqtt-subscriber
    command: ./subscriber/sub_message.sh && exit  # run subscriber script
    depends_on:
      - mqtt-broker
    volumes:
      - ./logs:/logs  # for mosquitto log
      - ./subscriber:/subscriber  # subscriber script
    environment:
      - TZ=Europe/Paris  # timezone setting
    networks: # for network delay setting
      - mqtt_network
    cap_add:
      - NET_ADMIN  # for network delay setting

networks:
  mqtt_network:
